### ISSUE TITLE
playback speed sounds like a chipmunk

### ISSUE THREAD

**Issue by texas697** [E-Kuerschner/useAudioPlayer#137]
Increasing the playing back rate makes the podcast sound like a chipmunk. Is there something different I need to be doing then increasing the rate?

these are speeds I am using

`export const DAISY_CAST_PLAYBACK_SPEEDS: number[] = [
  2, 1.75, 1.5, 1.25, 1, 0.75,
];`

"react-use-audio-player": "^2.2.0"

**Comment by E-Kuerschner** [comment]
Hey @texas697 - I believe that this is due to the technique the underlying lib uses for increasing the speed. As far as I know there is no way to increase speed without affecting pitch. I would suggest possibly moving your question over to [that repo](https://github.com/goldfire/howler.js). Thanks for the question!
