### ISSUE TITLE
Rewrite without React context

### ISSUE THREAD

**Issue by E-Kuerschner** [E-Kuerschner/useAudioPlayer#14]
Currently the library makes use of React context to maintain the state of the audio instance. This requires the portion of the app using this state to be wrapped in a context Provider. Since a howler is stored globally on the window after it is created would it be possible to axe the Provider and derive all state from the globally stored howl? This would improve the usability of this library as it is frustrating to have to wrap elements in Providers.

Perhaps removing the Provider may introduce the necessity of more hooks to recall previously created hooks. This may not be a bad thing and should be judged at the time if/when it comes up.

**Comment by rchrdnsh** [comment]
My only concern is that this approach would be able to get by the build step of meta frameworks like Gatsby. If that is the case, then cool 😎

**Comment by E-Kuerschner** [comment]
hey @rchrdnsh, I've actually never used Gatsby before, what is your concern specifically so I can do some more research?

From the browser's perspective not much would actually be changing. Since howler manages all its instances through a single global `Howler` object, I'm thinking it may not be necessary to have the Provider in the current implementation. The Provider's sole purpose is keeping state about the single loaded sound and provide an interface for interacting with it. I think a lot of that responsibility could be given to the `useAudioPlayer` hook itself. I won't know for sure until I maybe put together a POC though. Until then this is just a hypothesis.

**Comment by rchrdnsh** [comment]
Well, Gatsby generates a static version of a site, and then serves that static site to users, and while the static version is being served Gatsby re-hydrates an interactive version of the site...SSR, basically, just done at build time...but things like using ‘window’ of any other DOM stuff will break the build process because it is undefined, so any interactive code that is being added to a Gatsby site needs to be able to get past the build step, or be loaded later using suspense, or loadable components or something along those lines...I hope that makes sense :-)

**Comment by GriffinSauce** [comment]
@rchrdnsh as far as I can tell Howler [will not attach to the window](https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L2528) if it's not available. I'm currently using these hooks in a Next.js project that has no issues with server render. If you want I can test out doing a static render but it shouldn't make any difference.

@E-Kuerschner perhaps hooks like [useSWR](https://github.com/vercel/swr) can serve as inspiration, It's a data fetching hook and has a [global cache](https://github.com/vercel/swr/blob/master/src/config.ts#L11) so there's no context necessary to share data among hook calls.

> Perhaps removing the Provider may introduce the necessity of more hooks to recall previously created hooks. This may not be a bad thing and should be judged at the time if/when it comes up.

Could you elaborate on this? Would love to jam on a solution here :)

**Comment by E-Kuerschner** [comment]
@GriffinSauce thanks for the reply! I've been taking a break from development for a little bit, but would definitely be interested in returning to work on this refactor. 

I like how useSWR has an optional feature to provide global configuration via a Provider component which wraps the part of the app using the hooks. If anything, I think this is the inspiration I took away from reading through their docs.

I think if react-use-audio-player took the same approach (optional Provider) then the biggest challenge would be allowing developers to control the same audio source from different components. This is currently achieved solely by the Provider. It holds the state for the single, shared audio instance that all instances of the hooks (useAudioPlayer and useAudioPosition) subscribe to and mutate via interactions. I suppose it should be possible to use the Howler Global state in the browser to derive everything we need (maybe disregard what I said about a hook summoning other hooks).

**Comment by GriffinSauce** [comment]
That pattern with an optional provider sounds great, best of both worlds!

Ironically I've had to move on from using this hook because I need HLS streaming audio and Howler doesn't support that 😅 So I've created my own custom hook using hls.js - that said; I will have the same global player state challenge so I will report back what I come up with for that. 

The quick and dirty solution right now is to manage that externally with a Zustand story but it's pretty clunky, using the Howler state sounds great but might couple this hooks functionality too tightly to that lib.

**Comment by E-Kuerschner** [comment]
@GriffinSauce yeah def lemme know where your journey takes you! Glad you found something for your needs in the meantime.

I agree with you tho that relying on the Howler global state really does couple us with howler, but there may not be many other ways without doing a lot of the same work that howler already does yourself.
