### ISSUE TITLE
Rapid src changes creates duplicate players

### ISSUE THREAD

**Issue by joshcawthorne** [E-Kuerschner/useAudioPlayer#30]
**Describe the bug**
When using a redux state store for the URL in the player, if you update the URL repeatedly quick enough, it creates duplicate versions of the player which can no longer be controlled. I see that this was reported here: [https://github.com/E-Kuerschner/useAudioPlayer/issues/18](url), but using the latest version (0.0.15), I'm still facing the issue.

**To Reproduce**
I've created a small repo with my use-case for you, which can be viewed here: [https://github.com/joshcawthorne/useAudioPlayerDuplicationBug](url). It can also be accessed via this URL: [https://use-audio-player-duplcation-bug.netlify.com/](url).

To recreate, simply quickly press around on the different track links, if you do it quick enough for about 5-10 seconds, you'll start hearing duplicate versions of the player which are uncontrollable.

**Expected behavior**
One version of the player to only ever exist, no matter how many times the src is updated.

**Environment (please complete the following information):**
 - Browser/ browser version: Chrome 81
 - Library version: 0.0.15
 - React version: 16.13.1
 - Node version: 12.14.1

Thanks for all your work thus far - this is a really brilliant library!

**Comment by E-Kuerschner** [comment]
@joshcawthorne thanks for the issue! Yeah this is definitely something that we have noticed before. I think your description captures the essence of the problem though. I think rapidly loading different URLs eventually causes the duplicate as you pointed out.

Since howler keeps a cache of sound objects globally I think it should be possible to check this before creating a new sound to catch this condition.

**Comment by E-Kuerschner** [comment]
This should hopefully be put to rest. Let me know if you experience anything like this in >= 0.0.16
