### ISSUE TITLE
Help: Dunno what I'm doing here...

### ISSUE THREAD

**Issue by rchrdnsh** [E-Kuerschner/useAudioPlayer#49]
dunno how to make a seekable progress bar from your example. Here's what I'm trying to do:

```jsx
const ProgressSlider = () => {

  const { percentComplete, duration, position, seek } = useAudioPosition()

  const goToPosition = React.useCallback((percentage) => {
    seek(duration * percentage)
  }, [duration, seek])

  return (
    <input
      max={duration}
      min="0"
      step="1"
      type="range"
      value={position}
      onClick={goToPosition}
    />
  )
}
```

...but I don't know how to make the click handler work right...where does `percentage` come from? Is there a simpler way? Just trying to use a range input for now...

Getting this error when I click on the Progress Bar to move the audio around:

<img width="590" alt="Screen Shot 2020-09-18 at 6 58 16 PM" src="https://user-images.githubusercontent.com/7884263/93656687-fc5a7a80-f9e0-11ea-9b2d-c80d78e960b5.png">

...HALP??? XD

**Comment by E-Kuerschner** [comment]
@rchrdnsh ahh okay this is probably due to the poor example I have in the README.

In the example I had something like this:
```jsx
const goToPosition = React.useCallback((percentage) => {
        seek(duration * percentage)
    }, [duration, seek])

    return <ProgressBar percentComplete={percentComplete} onBarPositionClick={goToPosition} />
```
`ProgressBar` was a fictional component that I imagined existed the sake of the contrived example. So in this example the component called back with a percent to the `goToPosition` function. 

For your implementation you are using a range input slider. Your callback will likely be receiving an integer between the min and max attributes you set. You will need to calculate the new position value yourself given this data.

**Comment by E-Kuerschner** [comment]
closing
